### ISSUE TITLE
Use sphinx-gallery for examples 

### ISSUE THREAD

**Issue by prisae** [empymod/emg3d#45]
## ROADMAP

**Repo:** https://github.com/empymod/emg3d-gallery

**Deployed to:** https://empymod.github.io/emg3d-gallery

### ToDo's
- [x] Adjust emg3d-manual.
- [x] Create a deploy-script.
- [x] Adjust READMEs at https://github.com/empymod/emg3d and at https://github.com/empymod/emg3d-gallery.
- [ ] Create an environment.yml and scripts to run all.
- [ ] Translate all notebooks.

### Status
- [x] 0a_Minimum_working_example.ipynb
- [x] 0b_Parameter_tests.ipynb
- [x] 0c_Total-vs-PS-Field.ipynb
- [x] 1a_1D_VTI_empymod.ipynb
- [ ] 1b_2D_triaxial_MARE2DEM.ipynb
- [ ] 1c_3D_triaxial_SimPEG.ipynb
- [ ] 1d_1D_VTI_empymod-Laplace.ipynb
- [ ] 2a_SEG-EAGE_3D-Salt-Model.ipynb
- [ ] 3a_GemPy-discretize-emg3d.ipynb
- [ ] 4a_RAM-requirements.ipynb
- [ ] 4b_Runtime.ipynb
- [ ] 4c_Check_boundary4airwave.ipynb
- [x] 5a_Obtaining_the_magnetic_field.ipynb
- [x] 5b_Magnetic_permeability.ipynb
- [ ] 5c_Magnetic_source_using_el_loop.ipynb
- [ ] 5d_Magnetic_source_using_duality.ipynb
- [ ] 6a_Fullspace.ipynb
- [ ] 6b_Marine-1D.ipynb

**Comment by prisae** [comment]
### => Automate it

**Comment by prisae** [comment]
If it can be made small enough, then include directly in docs. Restrictions (https://docs.readthedocs.io/en/stable/builds.html):
- 15 minutes
- 1 GB RAM

**Comment by prisae** [comment]
Wait with it for the moment.

There seems to be issues when building on Travis (https://github.com/numba/numba/issues/4908), keeps failing.

Also, would need to add `discretize` to the packages to install.

**Comment by prisae** [comment]
Following branch has everything to get started:
- https://github.com/empymod/emg3d/tree/sphinx-gallery

**Comment by prisae** [comment]
Closing this, as it is principally implemented. The remaining stuff moved over to issues in the emg3d-gallery repo.
